//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:49:45 PM CEST 
//


package org.taktik.icure.be.ehealth.dto.kmehr.v20171201.be.fgov.ehealth.standards.kmehr.cd.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CD-PATIENTWILL-RESvalues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CD-PATIENTWILL-RESvalues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="dnr0"/>
 *     &lt;enumeration value="dnr1"/>
 *     &lt;enumeration value="dnr2"/>
 *     &lt;enumeration value="dnr3"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CD-PATIENTWILL-RESvalues")
@XmlEnum
public enum CDPATIENTWILLRESvalues {

    @XmlEnumValue("dnr0")
    DNR_0("dnr0"),
    @XmlEnumValue("dnr1")
    DNR_1("dnr1"),
    @XmlEnumValue("dnr2")
    DNR_2("dnr2"),
    @XmlEnumValue("dnr3")
    DNR_3("dnr3");
    private final String value;

    CDPATIENTWILLRESvalues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDPATIENTWILLRESvalues fromValue(String v) {
        for (CDPATIENTWILLRESvalues c: CDPATIENTWILLRESvalues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
