//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.consultation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.taktik.icure.be.ehealth.samws.v2.company.submit.VatNrPerCountryType;


/**
 * <p>Java class for FindByCompanyType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="FindByCompanyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="CompanyActorNr" type="{urn:be:fgov:ehealth:samws:v2:core}CompanyActorNrType"/>
 *         &lt;element name="AnyNamePart" type="{urn:be:fgov:ehealth:samws:v2:core}SearchStringType"/>
 *         &lt;element name="VatNr" type="{urn:be:fgov:ehealth:samws:v2:company:submit}VatNrPerCountryType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FindByCompanyType", propOrder = {
    "vatNr",
    "anyNamePart",
    "companyActorNr"
})
public class FindByCompanyType
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "VatNr")
    protected VatNrPerCountryType vatNr;
    @XmlElement(name = "AnyNamePart")
    protected String anyNamePart;
    @XmlElement(name = "CompanyActorNr")
    protected String companyActorNr;

    /**
     * Gets the value of the vatNr property.
     *
     * @return
     *     possible object is
     *     {@link VatNrPerCountryType }
     *
     */
    public VatNrPerCountryType getVatNr() {
        return vatNr;
    }

    /**
     * Sets the value of the vatNr property.
     *
     * @param value
     *     allowed object is
     *     {@link VatNrPerCountryType }
     *
     */
    public void setVatNr(VatNrPerCountryType value) {
        this.vatNr = value;
    }

    /**
     * Gets the value of the anyNamePart property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getAnyNamePart() {
        return anyNamePart;
    }

    /**
     * Sets the value of the anyNamePart property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setAnyNamePart(String value) {
        this.anyNamePart = value;
    }

    /**
     * Gets the value of the companyActorNr property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getCompanyActorNr() {
        return companyActorNr;
    }

    /**
     * Sets the value of the companyActorNr property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setCompanyActorNr(String value) {
        this.companyActorNr = value;
    }

}
