//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.consultation;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for HasWadaClassificationType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="HasWadaClassificationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="WadaCode" type="{urn:be:fgov:ehealth:samws:v2:core}String10Type"/>
 *         &lt;element name="WadaName" type="{urn:be:fgov:ehealth:samws:v2:core}SearchStringType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "HasWadaClassificationType", propOrder = {
    "wadaName",
    "wadaCode"
})
public class HasWadaClassificationType
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "WadaName")
    protected String wadaName;
    @XmlElement(name = "WadaCode")
    protected String wadaCode;

    /**
     * Gets the value of the wadaName property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWadaName() {
        return wadaName;
    }

    /**
     * Sets the value of the wadaName property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWadaName(String value) {
        this.wadaName = value;
    }

    /**
     * Gets the value of the wadaCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getWadaCode() {
        return wadaCode;
    }

    /**
     * Sets the value of the wadaCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setWadaCode(String value) {
        this.wadaCode = value;
    }

}
