/*
 *  iCure Data Stack. Copyright (c) 2020 Taktik SA
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful, but
 *     WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *     Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public
 *     License along with this program.  If not, see
 *     <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.refdata;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.taktik.icure.be.ehealth.samws.v2.core.Text255Type;


/**
 * <p>Java class for DeviceTypeType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="DeviceTypeType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:refdata}DeviceTypeKeyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{urn:be:fgov:ehealth:samws:v2:core}Text255Type"/>
 *         &lt;element name="EdqmCode" type="{urn:be:fgov:ehealth:samws:v2:core}String20Type" minOccurs="0"/>
 *         &lt;element name="EdqmDefinition" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DeviceTypeType", propOrder = {
    "name",
    "edqmCode",
    "edqmDefinition"
})
public class DeviceTypeType
    extends DeviceTypeKeyType
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "Name", required = true)
    protected Text255Type name;
    @XmlElement(name = "EdqmCode")
    protected String edqmCode;
    @XmlElement(name = "EdqmDefinition")
    protected String edqmDefinition;

    /**
     * Gets the value of the name property.
     *
     * @return
     *     possible object is
     *     {@link Text255Type }
     *
     */
    public Text255Type getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     *
     * @param value
     *     allowed object is
     *     {@link Text255Type }
     *
     */
    public void setName(Text255Type value) {
        this.name = value;
    }

    /**
     * Gets the value of the edqmCode property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEdqmCode() {
        return edqmCode;
    }

    /**
     * Sets the value of the edqmCode property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEdqmCode(String value) {
        this.edqmCode = value;
    }

    /**
     * Gets the value of the edqmDefinition property.
     *
     * @return
     *     possible object is
     *     {@link String }
     *
     */
    public String getEdqmDefinition() {
        return edqmDefinition;
    }

    /**
     * Sets the value of the edqmDefinition property.
     *
     * @param value
     *     allowed object is
     *     {@link String }
     *
     */
    public void setEdqmDefinition(String value) {
        this.edqmDefinition = value;
    }

}
