//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.refdata;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SetFamhpReferencesRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SetFamhpReferencesRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetFamhpMainEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetFamhpAdditionalEntities"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SetFamhpReferencesRequestType", propOrder = {
    "atcClassifications",
    "deliveryModuses",
    "deliveryModusSpecifications",
    "deviceTypes",
    "packagingClosures",
    "packagingMaterials",
    "packagingTypes",
    "pharmaceuticalForms",
    "routeOfAdministrations",
    "substances",
    "standardForms",
    "standardRoutes",
    "standardSubstances",
    "standardUnits"
})
@XmlRootElement(name = "SetFamhpReferencesRequest")
public class SetFamhpReferencesRequest
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "AtcClassification")
    protected List<AtcClassificationType> atcClassifications;
    @XmlElement(name = "DeliveryModus")
    protected List<DeliveryModusType> deliveryModuses;
    @XmlElement(name = "DeliveryModusSpecification")
    protected List<DeliveryModusSpecificationType> deliveryModusSpecifications;
    @XmlElement(name = "DeviceType")
    protected List<DeviceTypeType> deviceTypes;
    @XmlElement(name = "PackagingClosure")
    protected List<PackagingClosureType> packagingClosures;
    @XmlElement(name = "PackagingMaterial")
    protected List<PackagingMaterialType> packagingMaterials;
    @XmlElement(name = "PackagingType")
    protected List<PackagingTypeType> packagingTypes;
    @XmlElement(name = "PharmaceuticalForm")
    protected List<PharmaceuticalFormType> pharmaceuticalForms;
    @XmlElement(name = "RouteOfAdministration")
    protected List<RouteOfAdministrationType> routeOfAdministrations;
    @XmlElement(name = "Substance")
    protected List<SubstanceType> substances;
    @XmlElement(name = "StandardForm")
    protected List<StandardFormFamhpType> standardForms;
    @XmlElement(name = "StandardRoute")
    protected List<StandardRouteFamhpType> standardRoutes;
    @XmlElement(name = "StandardSubstance")
    protected List<StandardSubstanceFamhpType> standardSubstances;
    @XmlElement(name = "StandardUnit")
    protected List<StandardUnitFamhpType> standardUnits;

    /**
     * Gets the value of the atcClassifications property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atcClassifications property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtcClassifications().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtcClassificationType }
     *
     *
     */
    public List<AtcClassificationType> getAtcClassifications() {
        if (atcClassifications == null) {
            atcClassifications = new ArrayList<AtcClassificationType>();
        }
        return this.atcClassifications;
    }

    /**
     * Gets the value of the deliveryModuses property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryModuses property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryModuses().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryModusType }
     *
     *
     */
    public List<DeliveryModusType> getDeliveryModuses() {
        if (deliveryModuses == null) {
            deliveryModuses = new ArrayList<DeliveryModusType>();
        }
        return this.deliveryModuses;
    }

    /**
     * Gets the value of the deliveryModusSpecifications property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryModusSpecifications property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryModusSpecifications().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryModusSpecificationType }
     *
     *
     */
    public List<DeliveryModusSpecificationType> getDeliveryModusSpecifications() {
        if (deliveryModusSpecifications == null) {
            deliveryModusSpecifications = new ArrayList<DeliveryModusSpecificationType>();
        }
        return this.deliveryModusSpecifications;
    }

    /**
     * Gets the value of the deviceTypes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceTypes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceTypes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceTypeType }
     *
     *
     */
    public List<DeviceTypeType> getDeviceTypes() {
        if (deviceTypes == null) {
            deviceTypes = new ArrayList<DeviceTypeType>();
        }
        return this.deviceTypes;
    }

    /**
     * Gets the value of the packagingClosures property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingClosures property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingClosures().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingClosureType }
     *
     *
     */
    public List<PackagingClosureType> getPackagingClosures() {
        if (packagingClosures == null) {
            packagingClosures = new ArrayList<PackagingClosureType>();
        }
        return this.packagingClosures;
    }

    /**
     * Gets the value of the packagingMaterials property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingMaterials property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingMaterials().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingMaterialType }
     *
     *
     */
    public List<PackagingMaterialType> getPackagingMaterials() {
        if (packagingMaterials == null) {
            packagingMaterials = new ArrayList<PackagingMaterialType>();
        }
        return this.packagingMaterials;
    }

    /**
     * Gets the value of the packagingTypes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingTypes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingTypes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingTypeType }
     *
     *
     */
    public List<PackagingTypeType> getPackagingTypes() {
        if (packagingTypes == null) {
            packagingTypes = new ArrayList<PackagingTypeType>();
        }
        return this.packagingTypes;
    }

    /**
     * Gets the value of the pharmaceuticalForms property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pharmaceuticalForms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPharmaceuticalForms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PharmaceuticalFormType }
     *
     *
     */
    public List<PharmaceuticalFormType> getPharmaceuticalForms() {
        if (pharmaceuticalForms == null) {
            pharmaceuticalForms = new ArrayList<PharmaceuticalFormType>();
        }
        return this.pharmaceuticalForms;
    }

    /**
     * Gets the value of the routeOfAdministrations property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeOfAdministrations property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteOfAdministrations().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteOfAdministrationType }
     *
     *
     */
    public List<RouteOfAdministrationType> getRouteOfAdministrations() {
        if (routeOfAdministrations == null) {
            routeOfAdministrations = new ArrayList<RouteOfAdministrationType>();
        }
        return this.routeOfAdministrations;
    }

    /**
     * Gets the value of the substances property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substances property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstances().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceType }
     *
     *
     */
    public List<SubstanceType> getSubstances() {
        if (substances == null) {
            substances = new ArrayList<SubstanceType>();
        }
        return this.substances;
    }

    /**
     * Gets the value of the standardForms property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardForms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardForms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardFormFamhpType }
     *
     *
     */
    public List<StandardFormFamhpType> getStandardForms() {
        if (standardForms == null) {
            standardForms = new ArrayList<StandardFormFamhpType>();
        }
        return this.standardForms;
    }

    /**
     * Gets the value of the standardRoutes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardRoutes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardRoutes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardRouteFamhpType }
     *
     *
     */
    public List<StandardRouteFamhpType> getStandardRoutes() {
        if (standardRoutes == null) {
            standardRoutes = new ArrayList<StandardRouteFamhpType>();
        }
        return this.standardRoutes;
    }

    /**
     * Gets the value of the standardSubstances property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardSubstances property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardSubstances().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardSubstanceFamhpType }
     *
     *
     */
    public List<StandardSubstanceFamhpType> getStandardSubstances() {
        if (standardSubstances == null) {
            standardSubstances = new ArrayList<StandardSubstanceFamhpType>();
        }
        return this.standardSubstances;
    }

    /**
     * Gets the value of the standardUnits property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardUnits property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardUnits().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardUnitFamhpType }
     *
     *
     */
    public List<StandardUnitFamhpType> getStandardUnits() {
        if (standardUnits == null) {
            standardUnits = new ArrayList<StandardUnitFamhpType>();
        }
        return this.standardUnits;
    }

}
