//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.refdata;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UnsetBcpiReferencesRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="UnsetBcpiReferencesRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}UnsetBcpiMainEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}UnsetBcpiAdditionalEntities"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UnsetBcpiReferencesRequestType", propOrder = {
    "noSwitchReasons",
    "virtualForms",
    "wadas",
    "noGenericPrescriptionReasons",
    "standardForms",
    "standardRoutes",
    "standardSubstances"
})
@XmlRootElement(name = "UnsetBcpiReferencesRequest")
public class UnsetBcpiReferencesRequest
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "NoSwitchReason")
    protected List<NoSwitchReasonKeyType> noSwitchReasons;
    @XmlElement(name = "VirtualForm")
    protected List<VirtualFormKeyType> virtualForms;
    @XmlElement(name = "Wada")
    protected List<WadaKeyType> wadas;
    @XmlElement(name = "NoGenericPrescriptionReason")
    protected List<NoGenericPrescriptionReasonKeyType> noGenericPrescriptionReasons;
    @XmlElement(name = "StandardForm")
    protected List<StandardFormKeyBcpiType> standardForms;
    @XmlElement(name = "StandardRoute")
    protected List<StandardRouteKeyBcpiType> standardRoutes;
    @XmlElement(name = "StandardSubstance")
    protected List<StandardSubstanceKeyBcpiType> standardSubstances;

    /**
     * Gets the value of the noSwitchReasons property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noSwitchReasons property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoSwitchReasons().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoSwitchReasonKeyType }
     *
     *
     */
    public List<NoSwitchReasonKeyType> getNoSwitchReasons() {
        if (noSwitchReasons == null) {
            noSwitchReasons = new ArrayList<NoSwitchReasonKeyType>();
        }
        return this.noSwitchReasons;
    }

    /**
     * Gets the value of the virtualForms property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the virtualForms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVirtualForms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VirtualFormKeyType }
     *
     *
     */
    public List<VirtualFormKeyType> getVirtualForms() {
        if (virtualForms == null) {
            virtualForms = new ArrayList<VirtualFormKeyType>();
        }
        return this.virtualForms;
    }

    /**
     * Gets the value of the wadas property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wadas property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWadas().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WadaKeyType }
     *
     *
     */
    public List<WadaKeyType> getWadas() {
        if (wadas == null) {
            wadas = new ArrayList<WadaKeyType>();
        }
        return this.wadas;
    }

    /**
     * Gets the value of the noGenericPrescriptionReasons property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noGenericPrescriptionReasons property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoGenericPrescriptionReasons().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoGenericPrescriptionReasonKeyType }
     *
     *
     */
    public List<NoGenericPrescriptionReasonKeyType> getNoGenericPrescriptionReasons() {
        if (noGenericPrescriptionReasons == null) {
            noGenericPrescriptionReasons = new ArrayList<NoGenericPrescriptionReasonKeyType>();
        }
        return this.noGenericPrescriptionReasons;
    }

    /**
     * Gets the value of the standardForms property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardForms property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardForms().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardFormKeyBcpiType }
     *
     *
     */
    public List<StandardFormKeyBcpiType> getStandardForms() {
        if (standardForms == null) {
            standardForms = new ArrayList<StandardFormKeyBcpiType>();
        }
        return this.standardForms;
    }

    /**
     * Gets the value of the standardRoutes property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardRoutes property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardRoutes().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardRouteKeyBcpiType }
     *
     *
     */
    public List<StandardRouteKeyBcpiType> getStandardRoutes() {
        if (standardRoutes == null) {
            standardRoutes = new ArrayList<StandardRouteKeyBcpiType>();
        }
        return this.standardRoutes;
    }

    /**
     * Gets the value of the standardSubstances property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardSubstances property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardSubstances().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardSubstanceKeyBcpiType }
     *
     *
     */
    public List<StandardSubstanceKeyBcpiType> getStandardSubstances() {
        if (standardSubstances == null) {
            standardSubstances = new ArrayList<StandardSubstanceKeyBcpiType>();
        }
        return this.standardSubstances;
    }

}
