/*
 *  iCure Data Stack. Copyright (c) 2020 Taktik SA
 *
 *     This program is free software: you can redistribute it and/or modify
 *     it under the terms of the GNU Affero General Public License as
 *     published by the Free Software Foundation, either version 3 of the
 *     License, or (at your option) any later version.
 *
 *     This program is distributed in the hope that it will be useful, but
 *     WITHOUT ANY WARRANTY; without even the implied warranty of
 *     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *     Affero General Public License for more details.
 *
 *     You should have received a copy of the GNU Affero General Public
 *     License along with this program.  If not, see
 *     <https://www.gnu.org/licenses/>.
 */

//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2019.05.22 at 08:11:32 PM CEST
//


package org.taktik.icure.be.ehealth.samws.v2.reimbursementlaw.submit;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SubmitReimbursementLawRequestType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="SubmitReimbursementLawRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LegalBasis" type="{urn:be:fgov:ehealth:samws:v2:reimbursementlaw:submit}SubmitLegalBasisType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SubmitReimbursementLawRequestType", propOrder = {
    "legalBasis"
})
@XmlRootElement(name = "SubmitReimbursementLawRequest")
public class SubmitReimbursementLawRequest
    implements Serializable
{

    private final static long serialVersionUID = 2L;
    @XmlElement(name = "LegalBasis", required = true)
    protected SubmitLegalBasisType legalBasis;

    /**
     * Gets the value of the legalBasis property.
     *
     * @return
     *     possible object is
     *     {@link SubmitLegalBasisType }
     *
     */
    public SubmitLegalBasisType getLegalBasis() {
        return legalBasis;
    }

    /**
     * Sets the value of the legalBasis property.
     *
     * @param value
     *     allowed object is
     *     {@link SubmitLegalBasisType }
     *
     */
    public void setLegalBasis(SubmitLegalBasisType value) {
        this.legalBasis = value;
    }

}
