//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.15 at 03:32:18 PM CEST 
//


package org.taktik.icure.be.samv2v5.entities;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CompanyKeyType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CompanyKeyType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="actorNr" use="required" type="{urn:be:fgov:ehealth:samws:v2:core}CompanyActorNrType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CompanyKeyType", namespace = "urn:be:fgov:ehealth:samws:v2:company:submit")
@XmlSeeAlso({
    CompanyFullDataType.class,
    RemoveCompanyType.class,
    CompanyType.class
})
public class CompanyKeyType {

    @XmlAttribute(name = "actorNr", required = true)
    protected String actorNr;

    /**
     * Gets the value of the actorNr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getActorNr() {
        return actorNr;
    }

    /**
     * Sets the value of the actorNr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setActorNr(String value) {
        this.actorNr = value;
    }

}
