//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.15 at 03:32:18 PM CEST
//


package org.taktik.icure.be.samv2v5.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExportReferencesType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExportReferencesType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}VersionedExportType">
 *       &lt;sequence>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetFamhpMainEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetBcpiMainEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}CommonAdditionalEntities"/>
 *         &lt;group ref="{urn:be:fgov:ehealth:samws:v2:refdata}SetNihdiEntities"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportReferencesType", propOrder = {
    "atcClassification",
    "deliveryModus",
    "deliveryModusSpecification",
    "deviceType",
    "packagingClosure",
    "packagingMaterial",
    "packagingType",
    "pharmaceuticalForm",
    "routeOfAdministration",
    "substance",
    "noSwitchReason",
    "virtualForm",
    "wada",
    "noGenericPrescriptionReason",
    "indication",
    "dosageParameter",
    "standardForm",
    "standardRoute",
    "standardSubstance",
    "standardUnit",
    "appendix",
    "formCategory",
    "parameter",
    "reimbursementCriterion"
})
@XmlRootElement(name = "ExportReferences")
public class ExportReferencesType
    extends VersionedExportType
{

    @XmlElement(name = "AtcClassification", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AtcClassificationType> atcClassification;
    @XmlElement(name = "DeliveryModus", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<DeliveryModusType> deliveryModus;
    @XmlElement(name = "DeliveryModusSpecification", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<DeliveryModusSpecificationType> deliveryModusSpecification;
    @XmlElement(name = "DeviceType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<DeviceTypeType> deviceType;
    @XmlElement(name = "PackagingClosure", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<PackagingClosureType> packagingClosure;
    @XmlElement(name = "PackagingMaterial", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<PackagingMaterialType> packagingMaterial;
    @XmlElement(name = "PackagingType", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<PackagingTypeType> packagingType;
    @XmlElement(name = "PharmaceuticalForm", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<PharmaceuticalFormType> pharmaceuticalForm;
    @XmlElement(name = "RouteOfAdministration", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<RouteOfAdministrationType> routeOfAdministration;
    @XmlElement(name = "Substance", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<SubstanceType> substance;
    @XmlElement(name = "NoSwitchReason", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<NoSwitchReasonType> noSwitchReason;
    @XmlElement(name = "VirtualForm", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<VirtualFormType> virtualForm;
    @XmlElement(name = "Wada", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<WadaType> wada;
    @XmlElement(name = "NoGenericPrescriptionReason", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<NoGenericPrescriptionReasonType> noGenericPrescriptionReason;
    @XmlElement(name = "Indication", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<IndicationType> indication;
    @XmlElement(name = "DosageParameter", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<DosageParameterType> dosageParameter;
    @XmlElement(name = "StandardForm", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<StandardFormCommonType> standardForm;
    @XmlElement(name = "StandardRoute", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<StandardRouteCommonType> standardRoute;
    @XmlElement(name = "StandardSubstance", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<StandardSubstanceCommonType> standardSubstance;
    @XmlElement(name = "StandardUnit", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<StandardUnitFamhpType> standardUnit;
    @XmlElement(name = "Appendix", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<AppendixType> appendix;
    @XmlElement(name = "FormCategory", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<FormCategoryType> formCategory;
    @XmlElement(name = "Parameter", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ParameterType> parameter;
    @XmlElement(name = "ReimbursementCriterion", namespace = "urn:be:fgov:ehealth:samws:v2:refdata")
    protected List<ReimbursementCriterionType> reimbursementCriterion;

    /**
     * Gets the value of the atcClassification property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the atcClassification property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAtcClassification().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AtcClassificationType }
     *
     *
     */
    public List<AtcClassificationType> getAtcClassification() {
        if (atcClassification == null) {
            atcClassification = new ArrayList<AtcClassificationType>();
        }
        return this.atcClassification;
    }

    /**
     * Gets the value of the deliveryModus property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryModus property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryModus().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryModusType }
     *
     *
     */
    public List<DeliveryModusType> getDeliveryModus() {
        if (deliveryModus == null) {
            deliveryModus = new ArrayList<DeliveryModusType>();
        }
        return this.deliveryModus;
    }

    /**
     * Gets the value of the deliveryModusSpecification property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deliveryModusSpecification property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeliveryModusSpecification().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeliveryModusSpecificationType }
     *
     *
     */
    public List<DeliveryModusSpecificationType> getDeliveryModusSpecification() {
        if (deliveryModusSpecification == null) {
            deliveryModusSpecification = new ArrayList<DeliveryModusSpecificationType>();
        }
        return this.deliveryModusSpecification;
    }

    /**
     * Gets the value of the deviceType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the deviceType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDeviceType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DeviceTypeType }
     *
     *
     */
    public List<DeviceTypeType> getDeviceType() {
        if (deviceType == null) {
            deviceType = new ArrayList<DeviceTypeType>();
        }
        return this.deviceType;
    }

    /**
     * Gets the value of the packagingClosure property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingClosure property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingClosure().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingClosureType }
     *
     *
     */
    public List<PackagingClosureType> getPackagingClosure() {
        if (packagingClosure == null) {
            packagingClosure = new ArrayList<PackagingClosureType>();
        }
        return this.packagingClosure;
    }

    /**
     * Gets the value of the packagingMaterial property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingMaterial property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingMaterial().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingMaterialType }
     *
     *
     */
    public List<PackagingMaterialType> getPackagingMaterial() {
        if (packagingMaterial == null) {
            packagingMaterial = new ArrayList<PackagingMaterialType>();
        }
        return this.packagingMaterial;
    }

    /**
     * Gets the value of the packagingType property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the packagingType property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPackagingType().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PackagingTypeType }
     *
     *
     */
    public List<PackagingTypeType> getPackagingType() {
        if (packagingType == null) {
            packagingType = new ArrayList<PackagingTypeType>();
        }
        return this.packagingType;
    }

    /**
     * Gets the value of the pharmaceuticalForm property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the pharmaceuticalForm property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPharmaceuticalForm().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PharmaceuticalFormType }
     *
     *
     */
    public List<PharmaceuticalFormType> getPharmaceuticalForm() {
        if (pharmaceuticalForm == null) {
            pharmaceuticalForm = new ArrayList<PharmaceuticalFormType>();
        }
        return this.pharmaceuticalForm;
    }

    /**
     * Gets the value of the routeOfAdministration property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeOfAdministration property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteOfAdministration().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteOfAdministrationType }
     *
     *
     */
    public List<RouteOfAdministrationType> getRouteOfAdministration() {
        if (routeOfAdministration == null) {
            routeOfAdministration = new ArrayList<RouteOfAdministrationType>();
        }
        return this.routeOfAdministration;
    }

    /**
     * Gets the value of the substance property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the substance property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSubstance().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link SubstanceType }
     *
     *
     */
    public List<SubstanceType> getSubstance() {
        if (substance == null) {
            substance = new ArrayList<SubstanceType>();
        }
        return this.substance;
    }

    /**
     * Gets the value of the noSwitchReason property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noSwitchReason property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoSwitchReason().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoSwitchReasonType }
     *
     *
     */
    public List<NoSwitchReasonType> getNoSwitchReason() {
        if (noSwitchReason == null) {
            noSwitchReason = new ArrayList<NoSwitchReasonType>();
        }
        return this.noSwitchReason;
    }

    /**
     * Gets the value of the virtualForm property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the virtualForm property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getVirtualForm().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link VirtualFormType }
     *
     *
     */
    public List<VirtualFormType> getVirtualForm() {
        if (virtualForm == null) {
            virtualForm = new ArrayList<VirtualFormType>();
        }
        return this.virtualForm;
    }

    /**
     * Gets the value of the wada property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the wada property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWada().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WadaType }
     *
     *
     */
    public List<WadaType> getWada() {
        if (wada == null) {
            wada = new ArrayList<WadaType>();
        }
        return this.wada;
    }

    /**
     * Gets the value of the noGenericPrescriptionReason property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the noGenericPrescriptionReason property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNoGenericPrescriptionReason().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NoGenericPrescriptionReasonType }
     *
     *
     */
    public List<NoGenericPrescriptionReasonType> getNoGenericPrescriptionReason() {
        if (noGenericPrescriptionReason == null) {
            noGenericPrescriptionReason = new ArrayList<NoGenericPrescriptionReasonType>();
        }
        return this.noGenericPrescriptionReason;
    }

    /**
     * Gets the value of the indication property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the indication property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIndication().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IndicationType }
     *
     *
     */
    public List<IndicationType> getIndication() {
        if (indication == null) {
            indication = new ArrayList<IndicationType>();
        }
        return this.indication;
    }

    /**
     * Gets the value of the dosageParameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dosageParameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDosageParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DosageParameterType }
     *
     *
     */
    public List<DosageParameterType> getDosageParameter() {
        if (dosageParameter == null) {
            dosageParameter = new ArrayList<DosageParameterType>();
        }
        return this.dosageParameter;
    }

    /**
     * Gets the value of the standardForm property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardForm property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardForm().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardFormCommonType }
     *
     *
     */
    public List<StandardFormCommonType> getStandardForm() {
        if (standardForm == null) {
            standardForm = new ArrayList<StandardFormCommonType>();
        }
        return this.standardForm;
    }

    /**
     * Gets the value of the standardRoute property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardRoute property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardRoute().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardRouteCommonType }
     *
     *
     */
    public List<StandardRouteCommonType> getStandardRoute() {
        if (standardRoute == null) {
            standardRoute = new ArrayList<StandardRouteCommonType>();
        }
        return this.standardRoute;
    }

    /**
     * Gets the value of the standardSubstance property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardSubstance property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardSubstance().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardSubstanceCommonType }
     *
     *
     */
    public List<StandardSubstanceCommonType> getStandardSubstance() {
        if (standardSubstance == null) {
            standardSubstance = new ArrayList<StandardSubstanceCommonType>();
        }
        return this.standardSubstance;
    }

    /**
     * Gets the value of the standardUnit property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the standardUnit property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStandardUnit().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link StandardUnitFamhpType }
     *
     *
     */
    public List<StandardUnitFamhpType> getStandardUnit() {
        if (standardUnit == null) {
            standardUnit = new ArrayList<StandardUnitFamhpType>();
        }
        return this.standardUnit;
    }

    /**
     * Gets the value of the appendix property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the appendix property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAppendix().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AppendixType }
     *
     *
     */
    public List<AppendixType> getAppendix() {
        if (appendix == null) {
            appendix = new ArrayList<AppendixType>();
        }
        return this.appendix;
    }

    /**
     * Gets the value of the formCategory property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formCategory property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormCategory().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FormCategoryType }
     *
     *
     */
    public List<FormCategoryType> getFormCategory() {
        if (formCategory == null) {
            formCategory = new ArrayList<FormCategoryType>();
        }
        return this.formCategory;
    }

    /**
     * Gets the value of the parameter property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ParameterType }
     *
     *
     */
    public List<ParameterType> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ParameterType>();
        }
        return this.parameter;
    }

    /**
     * Gets the value of the reimbursementCriterion property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the reimbursementCriterion property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReimbursementCriterion().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ReimbursementCriterionType }
     *
     *
     */
    public List<ReimbursementCriterionType> getReimbursementCriterion() {
        if (reimbursementCriterion == null) {
            reimbursementCriterion = new ArrayList<ReimbursementCriterionType>();
        }
        return this.reimbursementCriterion;
    }

}
