//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2020.10.15 at 03:32:18 PM CEST
//


package org.taktik.icure.be.samv2v5.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ExportCompoundingType complex type.
 *
 * <p>The following schema fragment specifies the expected content contained within this class.
 *
 * <pre>
 * &lt;complexType name="ExportCompoundingType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:export}VersionedExportType">
 *       &lt;sequence>
 *         &lt;element name="CompoundingIngredient" type="{urn:be:fgov:ehealth:samws:v2:export}CompoundingIngredientFullDataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="CompoundingFormula" type="{urn:be:fgov:ehealth:samws:v2:export}CompoundingFormulaFullDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ExportCompoundingType", propOrder = {
    "compoundingIngredient",
    "compoundingFormula"
})
@XmlRootElement(name = "ExportCompounding")
public class ExportCompoundingType
    extends VersionedExportType
{

    @XmlElement(name = "CompoundingIngredient")
    protected List<CompoundingIngredientFullDataType> compoundingIngredient;
    @XmlElement(name = "CompoundingFormula")
    protected List<CompoundingFormulaFullDataType> compoundingFormula;

    /**
     * Gets the value of the compoundingIngredient property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundingIngredient property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundingIngredient().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompoundingIngredientFullDataType }
     *
     *
     */
    public List<CompoundingIngredientFullDataType> getCompoundingIngredient() {
        if (compoundingIngredient == null) {
            compoundingIngredient = new ArrayList<CompoundingIngredientFullDataType>();
        }
        return this.compoundingIngredient;
    }

    /**
     * Gets the value of the compoundingFormula property.
     *
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the compoundingFormula property.
     *
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCompoundingFormula().add(newItem);
     * </pre>
     *
     *
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CompoundingFormulaFullDataType }
     *
     *
     */
    public List<CompoundingFormulaFullDataType> getCompoundingFormula() {
        if (compoundingFormula == null) {
            compoundingFormula = new ArrayList<CompoundingFormulaFullDataType>();
        }
        return this.compoundingFormula;
    }

}
