//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.15 at 03:32:18 PM CEST 
//


package org.taktik.icure.be.samv2v5.entities;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LegalBasisFullDataType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LegalBasisFullDataType">
 *   &lt;complexContent>
 *     &lt;extension base="{urn:be:fgov:ehealth:samws:v2:reimbursementlaw:submit}LegalBasisKeyType">
 *       &lt;sequence>
 *         &lt;element name="Data" type="{urn:be:fgov:ehealth:samws:v2:export}LegalBasisDataType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="LegalReference" type="{urn:be:fgov:ehealth:samws:v2:export}RecursiveLegalReferenceFullDataType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LegalBasisFullDataType", propOrder = {
    "data",
    "legalReference"
})
public class LegalBasisFullDataType
    extends LegalBasisKeyType
{

    @XmlElement(name = "Data")
    protected List<LegalBasisDataType> data;
    @XmlElement(name = "LegalReference")
    protected List<RecursiveLegalReferenceFullDataType> legalReference;

    /**
     * Gets the value of the data property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the data property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LegalBasisDataType }
     * 
     * 
     */
    public List<LegalBasisDataType> getData() {
        if (data == null) {
            data = new ArrayList<LegalBasisDataType>();
        }
        return this.data;
    }

    /**
     * Gets the value of the legalReference property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legalReference property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegalReference().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RecursiveLegalReferenceFullDataType }
     * 
     * 
     */
    public List<RecursiveLegalReferenceFullDataType> getLegalReference() {
        if (legalReference == null) {
            legalReference = new ArrayList<RecursiveLegalReferenceFullDataType>();
        }
        return this.legalReference;
    }

}
