/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as models from "./models"

export class Medication  {
  constructor(json: JSON | any) {
    Object.assign(this as Medication, json)
  }
  batch?: string

  beginMoment?: number

  commentForDelivery?: string

  compoundPrescription?: string

  compoundPrescriptionV2?: models.CompoundPrescription

  duration?: models.Duration

  endMoment?: number

  instructionForPatient?: string

  instructionsForReimbursement?: Medication.InstructionsForReimbursementEnum

  intakeRoute?: models.Code

  knownUsage?: boolean

  medicinalProduct?: models.Medicinalproduct

  numberOfPackages?: number

  options?: { [key: string]: models.Content }

  recipeInstructionForPatient?: string

  regimen?: Array<models.RegimenItem>

  renewal?: models.MedicationRenewal

  substanceProduct?: models.Substanceproduct

  substitutionAllowed?: boolean

  temporality?: models.Code
}
export namespace Medication {
  export enum InstructionsForReimbursementEnum {
    PAYINGTHIRDPARTY = <any>"PAYING_THIRD_PARTY",
    FIRSTDOSE = <any>"FIRST_DOSE",
    SECONDDOSE = <any>"SECOND_DOSE",
    THIRDDOSE = <any>"THIRD_DOSE",
    CHRONICKINDEYDISEASE = <any>"CHRONIC_KINDEY_DISEASE",
    DIABETESTREATMENT = <any>"DIABETES_TREATMENT",
    DIABETESCONVENTION = <any>"DIABETES_CONVENTION",
    NOTREIMBURSABLE = <any>"NOT_REIMBURSABLE"
  }
}
