//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.06.14 at 03:49:25 PM CEST 
//


package org.taktik.icure.be.ehealth.dto.kmehr.v20150901.be.fgov.ehealth.standards.kmehr.cd.v1;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CD-BVT-SAMPLETYPEvalues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CD-BVT-SAMPLETYPEvalues">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="primarytumor"/>
 *     &lt;enumeration value="metastasis"/>
 *     &lt;enumeration value="normaltissue"/>
 *     &lt;enumeration value="other"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CD-BVT-SAMPLETYPEvalues")
@XmlEnum
public enum CDBVTSAMPLETYPEvalues {

    @XmlEnumValue("primarytumor")
    PRIMARYTUMOR("primarytumor"),
    @XmlEnumValue("metastasis")
    METASTASIS("metastasis"),
    @XmlEnumValue("normaltissue")
    NORMALTISSUE("normaltissue"),
    @XmlEnumValue("other")
    OTHER("other");
    private final String value;

    CDBVTSAMPLETYPEvalues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CDBVTSAMPLETYPEvalues fromValue(String v) {
        for (CDBVTSAMPLETYPEvalues c: CDBVTSAMPLETYPEvalues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
