/**
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import {XHR} from "./XHR"
import * as models from '../model/models';

export class iccCodeApi {
    host : string
    headers : Array<XHR.Header>
    constructor(host: string, headers: any) {
        this.host = host
        this.headers = Object.keys(headers).map(k => new XHR.Header(k,headers[k]))
    }


    handleError(e: XHR.Data) {
        if (e.status == 401) throw Error('auth-failed')
        else throw Error('api-error'+ e.status)
    }


    createCode(body?: models.CodeDto) : Promise<models.CodeDto|any> {
        let _body = null
        _body = body
        
        const _url = this.host+"/code" + "?ts=" + (new Date).getTime() 

        return XHR.sendCommand('POST', _url , this.headers, _body )
                .then(doc =>  new models.CodeDto(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
    findCodeTypes(region?: string, type?: string) : Promise<Array<string>|any> {
        let _body = null
        
        
        const _url = this.host+"/code/codetype/byRegionType" + "?ts=" + (new Date).getTime()  + (region ? "&region=" + region : "") + (type ? "&type=" + type : "")

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc => (doc.body as Array<JSON>).map(it=>JSON.parse(JSON.stringify(it))))
                .catch(err => this.handleError(err))


    }
    findCodes(region?: string, type?: string, code?: string, version?: string) : Promise<Array<models.CodeDto>|any> {
        let _body = null
        
        
        const _url = this.host+"/code/byRegionTypeCode" + "?ts=" + (new Date).getTime()  + (region ? "&region=" + region : "") + (type ? "&type=" + type : "") + (code ? "&code=" + code : "") + (version ? "&version=" + version : "")

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc => (doc.body as Array<JSON>).map(it=>new models.CodeDto(it)))
                .catch(err => this.handleError(err))


    }
    findPaginatedCodes(region?: string, type?: string, code?: string, version?: string, startDocumentId?: string, limit?: number) : Promise<models.CodePaginatedList|any> {
        let _body = null
        
        
        const _url = this.host+"/code" + "?ts=" + (new Date).getTime()  + (region ? "&region=" + region : "") + (type ? "&type=" + type : "") + (code ? "&code=" + code : "") + (version ? "&version=" + version : "") + (startDocumentId ? "&startDocumentId=" + startDocumentId : "") + (limit ? "&limit=" + limit : "")

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc =>  new models.CodePaginatedList(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
    findPaginatedCodesByLabel(region?: string, types?: string, language?: string, label?: string, startDocumentId?: string, limit?: number) : Promise<models.CodePaginatedList|any> {
        let _body = null
        
        
        const _url = this.host+"/code/byLabel" + "?ts=" + (new Date).getTime()  + (region ? "&region=" + region : "") + (types ? "&types=" + types : "") + (language ? "&language=" + language : "") + (label ? "&label=" + label : "") + (startDocumentId ? "&startDocumentId=" + startDocumentId : "") + (limit ? "&limit=" + limit : "")

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc =>  new models.CodePaginatedList(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
    findTagTypes(region?: string, type?: string) : Promise<Array<string>|any> {
        let _body = null
        
        
        const _url = this.host+"/code/tagtype/byRegionType" + "?ts=" + (new Date).getTime()  + (region ? "&region=" + region : "") + (type ? "&type=" + type : "")

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc => (doc.body as Array<JSON>).map(it=>JSON.parse(JSON.stringify(it))))
                .catch(err => this.handleError(err))


    }
    getCode(codeId: string) : Promise<models.CodeDto|any> {
        let _body = null
        
        
        const _url = this.host+"/code/{codeId}".replace("{codeId}", codeId+"") + "?ts=" + (new Date).getTime() 

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc =>  new models.CodeDto(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
    getCodeWithParts(type: string, code: string, version: string) : Promise<models.CodeDto|any> {
        let _body = null
        
        
        const _url = this.host+"/code/{type}/{code}/{version}".replace("{type}", type+"").replace("{code}", code+"").replace("{version}", version+"") + "?ts=" + (new Date).getTime() 

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc =>  new models.CodeDto(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
    getCodes(codeIds: string) : Promise<Array<models.CodeDto>|any> {
        let _body = null
        
        
        const _url = this.host+"/code/byIds/{codeIds}".replace("{codeIds}", codeIds+"") + "?ts=" + (new Date).getTime() 

        return XHR.sendCommand('GET', _url , this.headers, _body )
                .then(doc => (doc.body as Array<JSON>).map(it=>new models.CodeDto(it)))
                .catch(err => this.handleError(err))


    }
    modifyCode(body?: models.CodeDto) : Promise<models.CodeDto|any> {
        let _body = null
        _body = body
        
        const _url = this.host+"/code" + "?ts=" + (new Date).getTime() 

        return XHR.sendCommand('PUT', _url , this.headers, _body )
                .then(doc =>  new models.CodeDto(doc.body as JSON))
                .catch(err => this.handleError(err))


    }
}

