/*
 * Copyright (C) 2018 Taktik SA
 *
 * This file is part of iCureBackend.
 *
 * iCureBackend is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 2 as published by
 * the Free Software Foundation.
 *
 * iCureBackend is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with iCureBackend.  If not, see <http://www.gnu.org/licenses/>.
 */


package org.taktik.icure.be.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import org.taktik.icure.be.drugs.dto.EquivalenceId;

/**
 * Equivalence generated by hbm2java
 */
public class Equivalence  implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
     private EquivalenceId id;
     private Mp mpBySourceequivalence;
     private Mp mpByTargetequivalence;
     private String type;

    public Equivalence() {
    }

	
    public Equivalence(EquivalenceId id, Mp mpBySourceequivalence, Mp mpByTargetequivalence) {
        this.id = id;
        this.mpBySourceequivalence = mpBySourceequivalence;
        this.mpByTargetequivalence = mpByTargetequivalence;
    }
    public Equivalence(EquivalenceId id, Mp mpBySourceequivalence, Mp mpByTargetequivalence, String type) {
       this.id = id;
       this.mpBySourceequivalence = mpBySourceequivalence;
       this.mpByTargetequivalence = mpByTargetequivalence;
       this.type = type;
    }
   
    public EquivalenceId getId() {
        return this.id;
    }
    
    public void setId(EquivalenceId id) {
        this.id = id;
    }
    public Mp getMpBySourceequivalence() {
        return this.mpBySourceequivalence;
    }
    
    public void setMpBySourceequivalence(Mp mpBySourceequivalence) {
        this.mpBySourceequivalence = mpBySourceequivalence;
    }
    public Mp getMpByTargetequivalence() {
        return this.mpByTargetequivalence;
    }
    
    public void setMpByTargetequivalence(Mp mpByTargetequivalence) {
        this.mpByTargetequivalence = mpByTargetequivalence;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }




}


