/*
 * Copyright (C) 2018 Taktik SA
 *
 * This file is part of iCureBackend.
 *
 * Foobar is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Foobar is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with iCureBackend.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * Copyright (C) 2018 Taktik SA
 *
 * This file is part of iCureBackend.
 *
 * Foobar is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 2 of the License, or
 * (at your option) any later version.
 *
 * Foobar is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with iCureBackend.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.taktik.icure.be.drugs;
// Generated Feb 27, 2008 11:38:04 AM by Hibernate Tools 3.2.0.CR1


import java.util.HashSet;
import java.util.Set;
import java.util.SortedSet;
import java.util.TreeSet;

import org.taktik.icure.be.drugs.dto.MpId;

/**
 * Mp generated by hbm2java
 */
public class Mp implements java.io.Serializable,Comparable<Mp> {

	private static final long serialVersionUID = 1L;
     private MpId id;
     private Doc doc;
     private Informationresponsible infoResp;
     private String name;
     private String vaccinecode;
     private String pos;
     private String note;
     private String equiv;
     private String dopingcode;
     private String type;
     private Set<Equivalence> equivalencesForTargetequivalence = new HashSet<Equivalence>(0);
     private SortedSet<Mpp> mpps = new TreeSet<Mpp>();
     private Set<Equivalence> equivalencesForSourceequivalence = new HashSet<Equivalence>(0);

    public Mp() {
    }


    public MpId getId() {
        return this.id;
    }
    
    public void setId(MpId id) {
        this.id = id;
    }
    public Doc getDoc() {
        return this.doc;
    }
    
    public void setDoc(Doc doc) {
        this.doc = doc;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getVaccinecode() {
        return this.vaccinecode;
    }
    
    public void setVaccinecode(String vaccinecode) {
        this.vaccinecode = vaccinecode;
    }
    public String getPos() {
        return this.pos;
    }
    
    public void setPos(String pos) {
        this.pos = pos;
    }
    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
    public String getEquiv() {
        return this.equiv;
    }
    
    public void setEquiv(String equiv) {
        this.equiv = equiv;
    }
    public String getDopingcode() {
        return this.dopingcode;
    }
    
    public void setDopingcode(String dopingcode) {
        this.dopingcode = dopingcode;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public Set<Equivalence> getEquivalencesForTargetequivalence() {
        return this.equivalencesForTargetequivalence;
    }
    
    public void setEquivalencesForTargetequivalence(Set<Equivalence> equivalencesForTargetequivalence) {
        this.equivalencesForTargetequivalence = equivalencesForTargetequivalence;
    }
    public SortedSet<Mpp> getMpps() {
        return this.mpps;
    }
    
    public void setMpps(SortedSet<Mpp> mpps) {
        this.mpps = mpps;
    }
    public Set<Equivalence> getEquivalencesForSourceequivalence() {
        return this.equivalencesForSourceequivalence;
    }
    
    public void setEquivalencesForSourceequivalence(Set<Equivalence> equivalencesForSourceequivalence) {
        this.equivalencesForSourceequivalence = equivalencesForSourceequivalence;
    }

	public int compareTo(Mp o) {
		return this.getName().compareTo(o.getName());
	}


	public Informationresponsible getInfoResp() {
		return infoResp;
	}


	public void setInfoResp(Informationresponsible infoResp) {
		this.infoResp = infoResp;
	}

}


