//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.12 at 04:36:37 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:be:fgov:ehealth:samws:v2:export", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.taktik.icure.be.samv2v4.entities;
